version: '3.9'

networks:
  backend_network:
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - backend_network
    environment:
      DB_NAME: ${DB_NAME}
      DB_ADMIN_USER: ${DB_ADMIN_USER}
      DB_USER: ${DB_USER}
    secrets:
      - db_root_password
      - db_admin_password
      - db_user_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  wordpress:
    build: requirements/wordpress
    container_name: wordpress

  nginx:
    build: requirements/nginx
    container_name: nginx


secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  db_user_password:
    file: ./secrets/db_password.txt

volumes:
  db_data:
    driver: local