version: '3.9'

networks:
  backend_network:
    driver: bridge

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb

  wordpress:
    build: requirements/wordpress
    container_name: wordpress

  nginx:
    build: requirements/nginx
    container_name: nginx