networks:
  backend_network:
    driver: bridge
services:
  nginx:
    build: srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - backend_network
    restart: unless-stopped
  wordpress:
    build: srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - DB_HOST=${DB_HOST}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
    volumes:
      - wp_data:/var/www/html
  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - backend_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_USER=${DB_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  db_data:
  wp_data: