networks:
  backend_network:
    driver: bridge

services:

  nginx:
    build: srcs/requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - backend_network
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html

  wordpress:
    build: srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_EMAIL=${WP_EMAIL}
    secrets:
      - db_admin_password
      - wp_password
      - wp_admin_password
    volumes:
      - wp_data:/var/www/html


  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    networks:
      - backend_network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_USER=${DB_USER}
    secrets:
      - db_root_password
      - db_admin_password
      - db_user_password
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s





secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_admin_password:
    file: ./secrets/db_admin_password.txt
  db_user_password:
    file: ./secrets/db_password.txt
  wp_password:
    file: ./secrets/wp_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt


volumes:
  db_data:
  wp_data: